# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-30 09:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cashflow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value_date', models.DateField(default=django.utils.timezone.now)),
                ('cf_type', models.CharField(choices=[(b'Equity', b'Equity'), (b'Proceeds', b'Proceeds')], default=b'Equity', max_length=50)),
                ('cashflows', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('local_currency', models.CharField(choices=[(b'GBP', b'GBP'), (b'USD', b'USD'), (b'EUR', b'EUR'), (b'RMB', b'RMB')], default=b'GBP', max_length=50)),
                ('fund', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='cashflow',
            name='deal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dealcashflows.Deal'),
        ),
    ]
